/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.7 */
/* Thu Jan 16 20:05:10 2025 */

/* parameterized module instance */
pll __ (.CLKI( ), .CLKOP( ));
